name: Terrapin Package Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
      name: Checkout source

    - name: Build package with Oryx
      run:  docker run --volume $(pwd):/repo --volume /home/runner/outputfolder:/output --env PRE_BUILD_COMMAND='chmod +x .github/workflows/terrapin-prebuild && .github/workflows/terrapin-prebuild' mcr.microsoft.com/oryx/build:latest oryx build --package /repo --output /output -p registry=http:///api/registry

    - uses: jikuma/githubaction@v0.3.3-alpha
      name: Create release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Terrapin release'
        release_note: 'Job: 6df38239-c478-4d3c-85b8-a8f8222a2988 | Package: lodash@4.0.0 | Manager: Npm | Commit: ${{ github.sha }}'
        asset_filepath: '/home/runner/outputfolder/lodash-4.0.0.tgz'
        tag_name: v4.0.0+${{ github.sha }}
